version: '3'

services:

  client-namespace:
    container_name: client-namespace
    image: busybox:1.35.0
    command: sleep infinity
    cap_add:
    - NET_ADMIN
    networks:
      tunneling-demo:
        aliases:
        - client

  client:
    container_name: client
    image: redhat/ubi8:8.6
    command: sleep infinity
    cap_add:
    - NET_ADMIN
    network_mode: "service:client-namespace"
    depends_on:
    - client-namespace

  client-sidecar:
    container_name: client-sidecar
    image: envoyproxy/envoy:v1.23.0
    cap_add:
    - NET_ADMIN
    network_mode: "service:client-namespace"
    volumes:
    - ./sidecar.yaml:/etc/envoy/envoy.yaml
    - ./client.default.svc.cluster.local.crt:/etc/pki/tls/certs/client.default.svc.cluster.local.crt
    - ./client.default.svc.cluster.local.key:/etc/pki/tls/private/client.default.svc.cluster.local.key
    - ./root-ca.crt:/etc/pki/tls/certs/root-ca.crt
    depends_on:
    - client

  egress-gateway:
    container_name: egress-gateway
    image: envoyproxy/envoy:v1.23.0
    cap_add:
    - NET_ADMIN
    volumes:
    - ./gateway.yaml:/etc/envoy/envoy.yaml
    - ./egress-gateway.istio-system.svc.cluster.local.crt:/etc/pki/tls/certs/egress-gateway.istio-system.svc.cluster.local.crt
    - ./egress-gateway.istio-system.svc.cluster.local.key:/etc/pki/tls/private/egress-gateway.istio-system.svc.cluster.local.key
    - ./root-ca.crt:/etc/pki/tls/certs/root-ca.crt
    networks:
      tunneling-demo:
    depends_on:
    - client-sidecar

  tunnel-proxy:
    container_name: tunnel-proxy
    image: envoyproxy/envoy:v1.23.0
    cap_add:
    - NET_ADMIN
    volumes:
    - ../../proxy/envoy.yaml:/etc/envoy/envoy.yaml
    - ../../tunnel-proxy.crt:/etc/pki/tls/certs/tunnel-proxy-cert.pem
    - ../../tunnel-proxy.key:/etc/pki/tls/private/tunnel-proxy-key.pem
    networks:
      tunneling-demo:
    depends_on:
    - egress-gateway

networks:
  tunneling-demo:
